import type { Metadata } from 'next';
import { sen } from '@lib/fonts';
import '@styles/global.scss';
import Header from '@components/ui/Header';
import Footer from '@components/ui/Footer';

import { Locale, i18n } from '@/i18n.config';

export const metadata: Metadata = {
  title: 'Client Blog',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={sen.className}>
        <Header lang={params.lang} />
        <main>{children}</main>
        <Footer lang={params.lang} />
      </body>
    </html>
  );
}
