import type { Metadata } from 'next';
import {sen} from '@lib/fonts'
import '@styles/global.scss';
import { Header } from '@components/ui/Header';
import { Footer } from '@components/ui/Footer';



export const metadata: Metadata = {
  title: 'Client Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={sen.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
