import type { Metadata } from 'next';
import { Sen } from 'next/font/google';
import '@styles/global.scss';
import { Header } from '@components/ui/Header';

const sen = Sen({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Client Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={sen.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
