import type { Metadata } from 'next';
import { Sen } from 'next/font/google';
import './globals.css';

const sen = Sen({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Client Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={sen.className}>{children}</body>
    </html>
  );
}
